### ISSUE TITLE
errors

### ISSUE THREAD

**Issue by jimgwhit** [nova-framework/system#3]
@LuckyCyborg you have errors one at MakeModuleCommand.php

```
protected $moduleFolders = array(
        'Assets/',
        'Controllers/',
        'Console/',
        'Database/',
        'Database/Migrations/',
        'Database/Seeds/',
        'Language/'    ///////////missing comma
        'Providers/',
        'Views/',
    );
```
#### The things bellow are on Composer packages shipped by other developers:

In ContainerAwareEventDispatcher
is this correct

```
foreach ($this->listenerIds[$eventName] as $i => list($serviceId, $method, $priority)) {
```

in GeneratorDemo is

```
public function baz()
```

suppose to be

```
public function bar()
```

**Comment by LuckyCyborg** [comment]
You know that is a **Work In Progress**, right?

And that **ContainerAwareEventDispatcher**, the code is correct. :smirk: 

BTW, if you look for bugs on other Composer packages than that shipped by us, be gentle and ask for the authors of those packages. What connection I have with the development of **symfony/event-dispatcher** ?
